"""add_error_message_to_agent_comparisons

Revision ID: 20c47af31c71
Revises: 962ea2614a41
Create Date: 2025-10-21 19:01:34.468500

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "20c47af31c71"
down_revision = "962ea2614a41"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_comparisons", sa.Column("error_message", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_comparisons", "error_message")
    # ### end Alembic commands ###
