"""Add current_phase to agent_comparisons

Revision ID: 962ea2614a41
Revises: 003
Create Date: 2025-10-21 13:29:28.959983

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "962ea2614a41"
down_revision = "003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_comparisons",
        sa.Column("current_phase", sa.String(length=50), nullable=True),
    )
    op.alter_column(
        "agent_comparisons",
        "scenario_config",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agent_comparisons",
        "scenario_config",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_column("agent_comparisons", "current_phase")
    # ### end Alembic commands ###
